# -*- coding: utf-8 -*-
# Publication data transcribed from the lab's existing Publications page.
PUBS = [
 dict(y=2026, a="Yongbo Shin*, Hye-Ran Moon*, You Mie Lee, Myung Jin Son",
      t="Liver organoids for chemical risk assessment: biological fidelity, standardization, and context-of-use frameworks",
      j="Archives of Pharmacal Research", d="49: 941\u2013954",
      doi="https://doi.org/10.1007/s12272-026-01627-8", tags=["Equal contribution"]),
 dict(y=2026, a="Hak Jun Lee, Se Eung Ahn, Minhyuk Jung, Hye-ran Moon, Byunghoon Ryu",
      t="Flexible and wireless \u2018stick-and-detect\u2019 sensor node based on laser-induced graphene for real-time temperature monitoring toward cold chain applications",
      j="Chemical Engineering Journal", d="",
      doi="https://doi.org/10.1016/j.cej.2026.175415", tags=[]),
 dict(y=2026, a="Hye-ran Moon*, Zhenying Cai*, Bo Kyung Cho*, Hyeyoun Chang, Seung Taek Hong, Jean J. Zhao, Ick Chan Kwon, Thomas M. Roberts, Bumsoo Han, Ju Hee Ryu",
      t="Statin-dye conjugates for selective targeting of KRAS mutant cancer cells",
      j="PLoS ONE", d="21(1): e0340189",
      doi="https://doi.org/10.1371/journal.pone.0340189", tags=["Equal contribution"]),
 dict(y=2025, a="Hye-ran Moon*, Bo Kyung Cho*, Seung Hyun Kang, Ju Hee Ryu, Ick Chan Kwon",
      t="Targeting and exploiting macropinocytosis in cancer therapy",
      j="Journal of Controlled Release", d="113962",
      doi="https://doi.org/10.1016/j.jconrel.2025.113962", tags=["Equal contribution"]),
 dict(y=2025, a="Hye-ran Moon*, Yancheng Du*, Sae Rome Choi*, Seongmin Seo, Cih Cheng, Bennett D. Elzey, Jong Hyun Choi, Bumsoo Han",
      t="DNA Origami-Cyanine Nanocomplex for Precision Imaging of KRAS-Mutant Pancreatic Cancer Cells",
      j="Advanced Science", d="12(19): 2410278",
      doi="https://doi.org/10.1002/advs.202410278",
      tags=["Equal contribution", "Hot Topic: Microfluidics", "Frontispiece"]),
 dict(y=2024, a="Hye-ran Moon*, Seon Ju Mun*, Tae Hun Kim*, Hyemin Kim, Dukjin Kang, Suran Kim, Ji Hyun Shin, Dongho Choi, Sun-Ju Ahn, Myung Jin Son",
      t="Guidelines for manufacturing and application of organoids: Liver",
      j="International Journal of Stem Cells", d="17(2): 120",
      doi=None, tags=["Equal contribution"]),
 dict(y=2024, a="Hye-ran Moon, Byunghoon Ryu",
      t="Review of Laser-Induced Graphene (LIG) Produced on Eco-Friendly Substrates",
      j="International Journal of Precision Engineering and Manufacturing-Green Technology", d="1–16",
      doi="https://doi.org/10.1007/s40684-024-00595-y", tags=[]),
 dict(y=2024, a="Silpa Gampala, Hye-ran Moon, Randall Wireman, Jacqueline Peil, Sonia Kiran, Dana K. Mitchell, Kylee Brewster, et al.",
      t="New Ref-1/Ape1 Targeted Inhibitors Demonstrating Improved Potency for Clinical Applications in Multiple Cancer Types",
      j="Pharmacological Research", d="107092",
      doi="https://doi.org/10.1016/j.phrs.2024.107092", tags=[]),
 dict(y=2023, a="Hye-ran Moon, Nishanth Surianarayanan, Tarun Singh, Bumsoo Han",
      t="Microphysiological Systems as Reliable Drug Discovery and Evaluation Tools: Evolution from Innovation to Maturity",
      j="Biomicrofluidics", d="17(6)",
      doi="https://doi.org/10.1063/5.0179444", tags=[]),
 dict(y=2022, a="Hye-ran Moon, Soutick Saha, Andrew Mugler, Bumsoo Han",
      t="Cells function as a ternary logic gate to decide migration direction under integrated chemical and fluidic cues",
      j="Lab on a Chip", d="23(4): 631–644",
      doi="https://doi.org/10.1039/D2LC00807F", tags=["Lab on a Chip HOT Article 2023"]),
 dict(y=2023, a="Cih Cheng, Naomi Deneke, Hye-ran Moon, Sae Rome Choi, Natalia Ospina-Munoz, Bennett Elzey, Chelsea Davis, George T.-C. Chiu, Bumsoo Han",
      t="Inkjet-printed morphogenesis of tumor-stroma interface using bi-cellular bioinks of collagen-poly(N-isopropyl acrylamide-co-methyl methacrylate) mixture",
      j="Materials Today Advances", d="19: 100408", doi=None, tags=[]),
 dict(y=2023, a="Kshitiz Gupta, Hye-ran Moon, Zhengwei Chen, Bumsoo Han, Nicolas G. Green, Steven T. Wereley",
      t="Optically induced electrothermal microfluidic tweezers in bio-relevant media",
      j="Scientific Reports", d="13(1): 9819", doi=None, tags=[]),
 dict(y=2022, a="Soutick Saha, Hye-ran Moon, Bumsoo Han, Andrew Mugler",
      t="Deduction of signaling mechanism from cellular responses to multiple cues",
      j="npj Systems Biology and Applications", d="8(1): 1–10", doi=None, tags=[]),
 dict(y=2021, a="Hye-ran Moon*, Soutick Saha*, Andrew Mugler, Bumsoo Han",
      t="Signal processing capacity of the cellular sensory machinery regulates the accuracy of chemotaxis under complex cues",
      j="iScience", d="24(11): 103242",
      doi="https://doi.org/10.1016/j.isci.2021.103242", tags=["Equal contribution"]),
 dict(y=2021, a="Stephanie M. Venis, Hye-ran Moon, Yi Yang, Sagar M. Utturkar, Stephen F. Konieczny, Bumsoo Han",
      t="Engineering of a functional pancreatic acinus with reprogrammed cancer cells by induced PTF1a expression",
      j="Lab on a Chip", d="21(19): 3675–3685",
      doi="https://doi.org/10.1039/D1LC00350J", tags=["Journal cover"]),
 dict(y=2021, a="Silpa Gampala, Fenil Shah, Xiaoyu Lu, Hye-ran Moon, Olivia Babb, Nikkitha Umesh Ganesh, George Sandusky, et al.",
      t="Ref-1 redox activity alters cancer cell metabolism in pancreatic cancer: Exploiting this novel finding as a potential target",
      j="Journal of Experimental & Clinical Cancer Research", d="40(1): 1–24", doi=None, tags=[]),
 dict(y=2020, a="Hye-ran Moon*, Altug Ozcelikkale*, Yi Yang, Bennett D. Elzey, Stephen F. Konieczny, Bumsoo Han",
      t="An engineered pancreatic cancer model with intra-tumoral heterogeneity of driver mutations",
      j="Lab on a Chip", d="20(20): 3720–3732",
      doi="https://doi.org/10.1039/D0LC00707B", tags=["Equal contribution", "Journal back cover"]),
 dict(y=2020, a="Hye-ran Moon, Natalia Ospina-Muñoz, Victoria Noe-Kim, Yi Yang, Bennett D. Elzey, Stephen F. Konieczny, Bumsoo Han",
      t="Subtype-specific characterization of breast cancer invasion using a microfluidic tumor platform",
      j="PLoS ONE", d="15(6): e0234012",
      doi="https://doi.org/10.1371/journal.pone.0234012", tags=[]),
 dict(y=2019, a="Julien Varennes*, Hye-ran Moon*, Soutick Saha, Andrew Mugler, Bumsoo Han",
      t="Physical constraints on accuracy and persistence during breast cancer cell chemotaxis",
      j="PLoS Computational Biology", d="15(4): e1006961",
      doi="https://doi.org/10.1371/journal.pcbi.1006961", tags=["Equal contribution"]),
 dict(y=2017, a="Altug Ozcelikkale, Hye-ran Moon, Michael Linnes, Bumsoo Han",
      t="In vitro microfluidic models of tumor microenvironment to screen transport of drugs and nanoparticles",
      j="WIREs Nanomedicine and Nanobiotechnology", d="9(5): e1460",
      doi="https://doi.org/10.1002/wnan.1460", tags=["Top 20 most downloaded"]),
 dict(y=2015, a="Hye-ran Moon, Min-Ho Shin, Jae-Yong Lee, Kyu-Jin Jang, Young-Ok Chung, Young-Joo Kim",
      t="Design of integrated light guide plate with functional structure of enhanced diffusion length for ultra-slim LED backlight unit",
      j="Journal of Display Technology", d="11(1): 44–52", doi=None, tags=[]),
 dict(y=2014, a="Min-Ho Shin, Jae-Yong Lee, Hye-ran Moon, Young-Joo Kim",
      t="Proposal and design of hybrid light guide plate based on aspheric concave surface and micropatterns to improve illuminance and color uniformity for LED display",
      j="Japanese Journal of Applied Physics", d="53(8S2): 08MF01", doi=None, tags=[]),
]
